// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoh1p4TYYEYSy-upc2lZahtOJVBMrolR4',
    appId: '1:789018593784:android:b63aa94a7c9da009afee0d',
    messagingSenderId: '789018593784',
    projectId: 'chat-2a1e7',
    storageBucket: 'chat-2a1e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2PwRDA5SURsUBgvDyAiZoMyzddGcHt04',
    appId: '1:789018593784:ios:a26366424fba94d3afee0d',
    messagingSenderId: '789018593784',
    projectId: 'chat-2a1e7',
    storageBucket: 'chat-2a1e7.firebasestorage.app',
    androidClientId: '789018593784-9tee8aapn53flhnakic2e0e731s79q3r.apps.googleusercontent.com',
    iosClientId: '789018593784-9ptjjk35p5imdnat6kbssqil1c7efc1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

}